
interfaces:
  leaf1:
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1”, "server_clag"]
    peerlink:
      - name: "peerlink"
        members: ["swp3", "swp4"]
        clag_ip: "169.254.254.1"
    bond1:
      - name: "bond1”
        members: ["swp1", "swp2"]
        clag_id: "12”
    server_clag:
      - name: "server_clag"
        members: ["swp5"]
        clag_id: “5”
  leaf2:
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1”, "server_clag"]
    peerlink:
      - name: "peerlink"
        members: ["swp3", "swp4"]
        clag_ip: "169.254.254.2"
    bond1:
      - name: "bond1”
        members: ["swp1", "swp2"]
        clag_id: "12”
    server_clag:
      - name: "server_clag"
        members: ["swp5"]
        clag_id: “5”
  leaf3:
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1”, "server_clag"]
    peerlink:
      - name: "peerlink"
        members: ["swp3", "swp4"]
        clag_ip: "169.254.254.1"
    bond34:
      - name: "bond1”
        members: ["swp1", "swp2"]
        clag_id: “34”
    server_clag:
      - name: "server_clag"
        members: ["swp5"]
        clag_id: “5”
  leaf4:
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1", "server_clag"]
    peerlink:
      - name: "peerlink"
        members: ["swp3", "swp4"]
        clag_ip: "169.254.254.2"
    bond1:
      - name: "bond1"
        members: ["swp1", "swp2"]
        clag_id: “34”
    server_clag:
      - name: "server_clag"
        members: ["swp5"]
        clag_id: “5”
  leaf5:
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1", "server_clag"]
    peerlink:
      - name: "peerlink"
        members: ["swp3", "swp4"]
        clag_ip: "169.254.254.1"
    bond1:
      - name: "bond1"
        members: ["swp1", "swp2"]
        clag_id: “56”
    server_clag:
      - name: "server_clag"
        members: ["swp5"]
        clag_id: "5"
  leaf6:
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1", "server_clag"]
    peerlink:
      - name: "peerlink"
        members: ["swp3", "swp4"]
        clag_ip: "169.254.254.2"
    bond1:
      - name: "bond1"
        members: ["swp1", "swp2"]
        clag_id: “56”
    server_clag:
      - name: "server_clag"
        members: ["swp5"] 
        clag_id: “5”


addresses:
  leaf1:
    clag_ip: "169.254.254.1/30"
    clag_peer: "169.254.254.2"
    clag_mac: "44:38:39:ff:00:02"
    svi: "10.1.10.1/24"
  leaf2:
    clag_ip: "169.254.254.2/30"
    clag_peer: "169.254.254.1"
    clag_mac: "44:38:39:ff:00:02"
    svi: "10.1.10.2/24"
  leaf3:
    clag_ip: "169.254.254.1/30"
    clag_peer: "169.254.254.2"
    clag_mac: "44:38:39:ff:00:03"
    svi: "10.1.10.3/24"
  leaf4:
    clag_ip: "169.254.254.2/30"
    clag_peer: "169.254.254.1"
    clag_mac: "44:38:39:ff:00:03"
    svi: "10.1.10.4/24"
  leaf5:
    clag_ip: "169.254.254.1/30"
    clag_peer: "169.254.254.2"
    clag_mac: "44:38:39:ff:00:04"
    svi: "10.1.10.5/24"
  leaf6:
    clag_ip: "169.254.254.2/30"
    clag_peer: "169.254.254.1"
    clag_mac: "44:38:39:ff:00:04"
    svi: "10.1.10.6/24"