---
- hosts: network
  become: yes
  tasks:
    - name: copy ports.conf
      copy: src=roles/leafs/{{ansible_hostname}}/ports.conf dest=/etc/cumulus/

    - name: copy interfaces
      copy: src=roles/leafs/{{ansible_hostname}}/etc/network/interfaces.d/* dest=/etc/network/interfaces.d/

    - name: copy Quagga daemons
      copy: src=roles/leafs/{{ansible_hostname}}/daemons dest=/etc/quagga/

    - name: copy Quagga conf
      copy: src=roles/leafs/{{ansible_hostname}}/Quagga.conf dest=/etc/quagga/

    - name: reload switchd
      service: name=switchd state=restarted

    - name: reload networking
      command: ifreload -a

    - name: reload quagga
      service: name=quagga state=restarted

# playbook needs tested
