---
- hosts: network
  become: yes
  tasks:
    - name: copy ports.conf
      copy: src=roles/leafs/{{ansible_hostname}}/ports.conf dest=/etc/cumulus/
      notify: restart switchd

    - name: copy interfaces
      copy: src=roles/leafs/{{ansible_hostname}}/interfaces dest=/etc/network/
      notify: reload networking

    - name: copy Quagga daemons
      copy: src=roles/leafs/{{ansible_hostname}}/daemons dest=/etc/quagga/
      notify: restart quagga

    - name: copy Quagga configuration file
      copy: src=roles/leafs/{{ansible_hostname}}/Quagga.conf dest=/etc/quagga/
      notify: reload quagga