---
- hosts: spines
  sudo: yes
  roles:
    - common
    - spines
  handlers:
    - include: handlers/main.yml

- hosts: leafs
  sudo: yes
  roles:
    - common
    - leafs
  handlers:
    - include: handlers/main.yml

- hosts: servers
  sudo: yes
  roles:
    - servers
  handlers:
    - include: handlers/main.yml
