---
- hosts: leaf1
  sudo: yes
  handlers:
    - include: handlers/main.yml
  tasks:
    - name: Check if route map is applied
      shell: vtysh -c "show run" | grep prepend | wc -l
      register: prepend_count

    # The reason for using cl-bgp commands instead of using a Quagga template
    # Is because then two quagga templates will have to be maintained
    # Probably a good candidate for a module, but this works for now.
    # A smarter way to do this would be to load from Vars file to identify
    # the names of the peer-groups. Again, good enough for proof of concept
    - name: Apply route maps to drain traffic
      command: "{{item[0] | replace('%peer_group%', item[1])}}"
      with_nested:
        - ["cl-bgp route-map set prepend in neighbor %peer_group% ipv4 unicast",
           "cl-bgp route-map set prepend in neighbor %peer_group% ipv6 unicast",
           "cl-bgp route-map set prepend out neighbor %peer_group% ipv4 unicast",
           "cl-bgp route-map set prepend out neighbor %peer_group% ipv6 unicast"]
        - ["fabric", "servers"]
      when: prepend_count.stdout | int < 3

    - name: Save Quagga Config
      command: sudo cl-rctl write-config integrated
      when: prepend_count.stdout | int < 3      

    - name: Verify traffic is drained. This will take a moment...
      interface_stats:

    - name: Reboot!
      shell: sleep 2 && shutdown -r now "Ansible reboot triggered"
      async: 1
      poll: 0
      ignore_errors: true

    - name: Waiting for server to restore. Please stand by...
      local_action:
        wait_for
        host={{ansible_ssh_host}}
        port={{ ansible_ssh_port }}
        delay=60
      sudo: False

    - name: load vars
      include_vars: roles/leafs/vars/main.yml

    - name: Copy Quagga Configuration
      template: src=roles/leafs/templates/Quagga.conf.j2 dest=/etc/quagga/Quagga.conf
      notify: reload quagga



    